dist: bionic
before_script:
  - "docker version"
  - "curl https://raw.githubusercontent.com/vishnubob/wait-for-it/8ed92e8cab83cfed76ff012ed4a36cef74b28096/wait-for-it.sh > ${TRAVIS_HOME}/gopath/bin/wait-for-it.sh && chmod +x ${TRAVIS_HOME}/gopath/bin/wait-for-it.sh"
matrix:
  include:
    - language: java
      jdk:
        - "openjdk11"
      cache:
        directories:
          - "/home/travis/.m2"
      before_install:
        - "java -version"
        - sudo apt update && sudo apt install -y chromium-browser
      install:
        - "/bin/true"
      script:
        - "docker-compose up -d"
        - "wait-for-it.sh -t 30 127.0.0.1:35432 -- echo 'postgres is up'"
        - "wait-for-it.sh -t 30 127.0.0.1:36379 -- echo 'redis is up'"
        - "rm ~/.m2/settings.xml"
        - (cd aaa; ./mvnw clean package -Dcustom.selenium.headless=true)

    - language: javascript
      node_js:
        - "12.16.3"
      cache:
        directories:
          - "/home/travis/build/nkonev/videochat/frontend/node_modules"
      before_install:
        - "node --version"
      install:
        - "/bin/true"
      script:
        - "pwd"
        - (cd frontend; npm install && npm run build)

    - language: go
      sudo: required
      go:
        - "1.14.3"
      cache:
        directories:
          - "$GOPATH/pkg"
      before_install:
        - "go version"
      install:
        - "/bin/true"
      script:
        - "docker-compose up -d"
        - "wait-for-it.sh -t 30 127.0.0.1:35432 -- echo 'postgres is up'"
        - "wait-for-it.sh -t 30 127.0.0.1:36379 -- echo 'redis is up'"
        - "wait-for-it.sh -t 30 127.0.0.1:9000 -- echo 'minio is up'"
        - sudo -- bash -c "echo '127.0.0.1   api.site.local' >> /etc/hosts"
        - "rm -rf ./chat/proto"
        - "mkdir ./chat/proto || true"
        - "docker run -it --rm -v $PWD:/ws -w /ws znly/protoc:0.4.0 --go_out=plugins=grpc:chat/proto -I./protobuf ./protobuf/*.proto"
        - (cd chat; go test ./... -count=1 -test.v -test.timeout=20s)
        - docker logs videochat_postgres_1
        - (cd storage; go test ./... -count=1 -test.v -test.timeout=20s)
