language: java
dist: bionic
jdk:
  - "openjdk11"
node_js:
  - "12.16.3"
go:
  - "1.14.3"
cache:
  directories:
    - "/home/travis/build/nkonev/videochat/frontend/node_modules"
    - "/home/travis/.gradle"
    - "$GOPATH/pkg"
before_install:
  - "nvm install 12.16.3"
  - "nvm use 12.16.3"
  - "docker-compose up -d"
install:
  - "node --version"
  - "go version"
  - "java -version"
script:
  - "pwd"
  - (cd frontend; npm run build)
  - (cd gateway; ./mvnw clean package)
  - (cd aaa; ./mvnw clean package)
  - (cd chat; go test ./... -count=1)