dist: bionic
before_script:
  - "docker version"
  - "docker-compose up -d"
matrix:
  include:
    - language: java
      jdk:
        - "openjdk11"
      cache:
        directories:
          - "/home/travis/.m2"
      before_install:
        - "java -version"
        - sudo apt update && sudo apt install -y chromium-browser
      install:
        - "/bin/true"
      script:
        - "pwd"
        - "rm ~/.m2/settings.xml"
        - (cd aaa; ./mvnw clean package -Dcustom.selenium.headless=true)

    - language: javascript
      node_js:
        - "12.16.3"
      cache:
        directories:
          - "/home/travis/build/nkonev/videochat/frontend/node_modules"
      before_install:
        - "node --version"
      install:
        - "/bin/true"
      script:
        - "pwd"
        - (cd frontend; npm install && npm run build)

    - language: go
      go:
        - "1.14.3"
      cache:
        directories:
          - "$GOPATH/pkg"
      before_install:
        - "go version"
      install:
        - "/bin/true"
      script:
        - "pwd"
        - "rm -rf ./chat/proto"
        - "mkdir ./chat/proto || true"
        - "docker run -it --rm -v $PWD:/ws -w /ws znly/protoc:0.4.0 --go_out=plugins=grpc:chat/proto -I./protobuf ./protobuf/*.proto"
        - (cd chat; go test ./... -count=1)
