# This file used for both developer and demo purposes.
# It contains environment
version: '3.7'

services:
  traefik:
    image: traefik:v2.8.7
    hostname: traefik
    restart: unless-stopped
    # The Static Configuration
    command: --configFile=/traefik_conf/traefik.yml
    ports:
      - 0.0.0.0:8081:8081
    extra_hosts:
      # https://github.com/moby/moby/pull/40007
      # works on Docker for Mac 3.4.0 or Linux Docker 20.10.4
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./docker/traefik_conf:/traefik_conf:z
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    networks:
      backend:

  # static server
  frontend:
    image: nginx:1.23.1
    restart: unless-stopped
    ports:
      - 8082:8082
    volumes:
      - ./frontend-nginx:/usr/share/nginx/html:z
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf:z
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
  postgresql:
    image: postgres:14.5-alpine3.16
    restart: unless-stopped
    ports:
      - 35432:5432
    volumes:
      - ./docker/postgresql_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
      - postgres_data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  redis:
    image: redis:7.0.4-alpine3.16
    hostname: redis
    restart: unless-stopped
    ports:
      - 36379:6379
    volumes:
      - redis_data_dir:/data:z
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  minio:
    image: bitnami/minio:2022.8.11-debian-11-r0
    hostname: minio
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      backend:
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - minio_data:/data:z
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  rabbitmq:
    image: rabbitmq:3.9.22-management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 35672:15672
      - 36672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=videoChat
      - RABBITMQ_DEFAULT_PASS=videoChatPazZw0rd
    volumes:
      - rabbitmq_data_dir:/var/lib/rabbitmq/mnesia:z
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  livekit:
    image: livekit/livekit-server:v1.2.3
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./docker/livekit/livekit.yaml:/etc/livekit.yaml

  egress:
    image: livekit/egress:v1.4.3
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - 40000:40000
    networks:
      backend:
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
#      - "files.minio:minio"
    volumes:
      - ./docker/egress/config.yaml:/etc/egress/config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.34.0
    hostname: jaeger
    restart: unless-stopped
    ports:
      # https://www.jaegertracing.io/docs/1.33/deployment/
      - 16686:16686 # web ui
      - 14250:14250 # grpc collector over http
      - 6831:6831/udp
    networks:
      backend:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

volumes:
  postgres_data:
  redis_data_dir:
  minio_data:
  rabbitmq_data_dir:
  es_data_dir:

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
