port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
redis:
    address: redis:6379
    username: ""
    password: ""
    db: 2
keys:
    APIznJxWShGW3Kt: KEUUtCDVRqXk9me0Ok94g8G9xwtnjMeUxfNMy8dow6iA
logging:
  json: false
  level: info
