server:
  address: ":1236"
  shutdown.timeout: "10s"
  body.limit: "100G"
  contextPath: "/api"

# Rest client
http:
  maxIdleConns: 2
  idleConnTimeout: '10s'
  disableCompression: false

auth:
  exclude:
    - "^/storage/public.*"
    - "^/internal.*"

types:
  image:
    - ".jpg"
    - ".jpeg"
    - ".png"
  video:
    - ".mp4"
    - ".mkv"
    - ".webm"

rabbitmq:
  url: "amqp://videoChat:videoChatPazZw0rd@127.0.0.1:36672"

jaeger:
  host: "localhost"
  port: 6831

minio:
  internalEndpoint: 127.0.0.1:9000
  interContainerUrl: http://minio:9000
  publicUrl: http://127.0.0.1:8081/api/minio
  publicDownloadTtl: 24h
  publicUploadTtl: 24h
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  location: "europe-east"
  bucket:
    userAvatar: "user-avatar"
    chatAvatar: "chat-avatar"
    files: "files"
    filesPreview: "files-preview"
  cleaner:
    files:
      # Start every
      interval: 60s
    previews:
      # Start every
      interval: 60s

chat:
  url:
    base: "http://localhost:1235"
    access: "/internal/access"
    removeFileItem: "/internal/remove-file-item"
    checkChatExistsPath: "/internal/is-chat-exists"
aaa:
  url:
    base: "http://localhost:8060"
    getUsers: "/internal/user/list"

limits:
  enabled: false
  stat:
    dir: "."
  default:
    # 512 megabytes
    all.users.limit: 536870912

redis:
  address: :36379
  password: ""
  db: 3
  maxRetries: 10000
