#logging.level.root: trace
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:4432/chat?connectTimeout=10&socketTimeout=40
    username: chat
    password: password

server:
  port: 8384

grpc:
  port: 6565