log_level: debug
gst_debug: 1
api_key: your-api-key
api_secret: your-api-secret
ws_url: wss://your-livekit-url.com
redis:
  address: 192.168.65.2:6379
local_directory: /out/output
room_name: your-room
room_only: false
track_composite_only: false
track_only: false
file_only: false
stream_only: false
segments_only: false
muting: false