#logging.level.org.springframework.cloud.gateway.filter: trace

server:
  port: 8282

spring:
#  resources:
#    cache:
#      cachecontrol:
#        no-cache: false
#        max-age: 40s
#    static-locations: file:/home/nkonev/go_1_11/videochat/frontend-nginx/
  redis:
    port: 36379
  sleuth:
    sampler:
      probability: 1.0
      rate: 0
  application:
    name: gateway
  cloud:
    loadbalancer:
      cache:
        ttl: 30s
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - predicates:
            - Path=/api/chat
          uri: http://localhost:1235
          filters:
            - name: Retry
              args:
                methods: GET
        - predicates:
            - Path=/,/public/**
          uri: http://localhost:8081
# https://qua.name/antolius/spring-cloud-gateway-connection-header
#          filters:
#            - name: SetRequestHeader
#              args:
#                name: Connection
#                value: keep-alive
#      filter:
#        remove-hop-by-hop:
#          headers:
#            - te
#            - trailer
#            - proxy-authorization
#            - proxy-authenticate
#            - x-application-context
