server:
  address: ":1237"
  shutdownTimeout: "10s"
  bodyLimit: "100G"

auth:
  exclude:
    - "^/video/public.*"
    - "^/internal/.*"

jaeger:
  host: "localhost"
  port: 6831

chat:
  url:
    base: "http://localhost:1235"
    access: "/internal/access"
    isChatAdmin: "/internal/is-admin"

aaa:
  url:
    base: "http://localhost:8060"
    getUsers: "/internal/user/list"

livekit:
  api:
    key: "APIznJxWShGW3Kt"
    secret: "KEUUtCDVRqXk9me0Ok94g8G9xwtnjMeUxfNMy8dow6iA"
  url: "http://localhost:7880"

frontend:
  # in ion-sdk-js vp8 is default
  preferredCodec: h264
  resolution: h720
#  iceserver:
#    - server:
#        urls: ["stun:stun.l.google.com:19302"]

rabbitmq:
  url: "amqp://videoChat:videoChatPazZw0rd@127.0.0.1:36672"
  debug: true

syncNotificationPeriod: 2s