version: '3.7'

services:
  storage:
    image: nkonev/chat-storage:latest
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
    logging:
      driver: "journald"
      options:
        tag: chat-storage
    volumes:
      - ./storage.yml:/etc/storage.yml
    command: ["-config=/etc/storage.yml"]

networks:
  backend:
    driver: overlay
