version: '3.7'

services:
  video:
    image: nkonev/chat-video:latest
    networks:
      backend:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        # it's loadbalancing enabled only for getting git.json. You should balance through video-proxy for the proper websocket balancing !
        - "traefik.enable=true"
        - "traefik.http.services.video-service.loadbalancer.server.port=7001"
        - "traefik.http.middlewares.video-stripprefix-middleware.stripprefix.prefixes=/api,/video"
        - "traefik.http.routers.video-version-router.rule=Path(`/video/git.json`)"
        - "traefik.http.routers.video-version-router.entrypoints=http"
        - "traefik.http.routers.video-version-router.middlewares=video-stripprefix-middleware"

    ports:
      # turn port
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
      - target: 3478
        published: 3478
        protocol: tcp
        mode: host

      # webrtc single port
      - target: 5000
        published: 5000
        protocol: udp
        mode: host

    logging:
      driver: "journald"
      options:
        tag: chat-video
    volumes:
      - ./video.yml:/etc/video.yml
    command: ["-config=/etc/video.yml"]

networks:
  backend:
    driver: overlay
