version: '3.7'

services:
  aaa:
    image: nkonev/chat-aaa:latest
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.aaa-service.loadbalancer.server.port=8060"
        - "traefik.http.routers.aaa-router.rule=PathPrefix(`/api/login`) || Path(`/api/logout`) || PathPrefix(`/api/profile`) || PathPrefix(`/api/user`)"
        - "traefik.http.routers.aaa-router.entrypoints=http"
        - "traefik.http.middlewares.aaa-retry-middleware.retry.attempts=4"
        - "traefik.http.routers.aaa-router.middlewares=aaa-retry-middleware"
    environment:
      - _JAVA_OPTIONS=-Djava.security.egd=file:/dev/./urandom -Xms256m -Xmx512m -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=256M -XX:OnOutOfMemoryError="kill -9 %p" -Dnetworkaddress.cache.ttl=0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/aaa
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/aaa?connectTimeout=10&socketTimeout=40&ApplicationName=aaa-app
      - SPRING_REDIS_URL=redis://redis:6379/0
      - SPRING_MAIL_HOST=smtp.yandex.ru
      - CUSTOM_EMAIL_FROM=username@yandex.ru
      - SPRING_MAIL_USERNAME=username
      - SPRING_MAIL_PASSWORD=password
      - CUSTOM_BASE-URL=http://api.site.local:8080
      - MANAGEMENT_HEALTH_MAIL_ENABLED=false

    logging:
      driver: "journald"
      options:
        tag: chat-aaa

networks:
  backend:
    driver: overlay
