version: '3.7'

services:
  traefik:
    image: traefik:v2.4.8
    hostname: traefik
    # The Static Configuration
    command: --configFile=/traefik_conf/traefik.yml
    ports:
      - 8081:80
#      - 8010:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_conf:/traefik_conf
    networks:
      - traefik_backend
      - backend
    logging:
      driver: "journald"
      options:
        tag: chat-traefik

  postgresql:
    image: postgres:13.1
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-postgresql

  redis:
    image: redis:6.0.8
    hostname: redis
    volumes:
      - redis_data_dir:/data
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-redis

  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    hostname: minio
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - /mnt/chat-minio/data:/data
    command: ["server", "/data"]
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-minio

  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    hostname: jaeger
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-jaeger


volumes:
  postgres_data:
  redis_data_dir:

networks:
  backend:
    driver: overlay
  traefik_backend:
    external: true
    name: proxy_backend
