version: '3.7'

services:
  storage:
    image: nkonev/chat-storage:latest
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.storage-service.loadbalancer.server.port=1236"
        - "traefik.http.routers.storage-router.rule=PathPrefix(`/api/storage`)"
        - "traefik.http.routers.storage-router.entrypoints=http"
        - "traefik.http.middlewares.storage-auth-middleware.forwardauth.address=http://aaa:8060/internal/profile"
        - "traefik.http.middlewares.storage-auth-middleware.forwardauth.authRequestHeaders=Cookie"
        - "traefik.http.middlewares.storage-auth-middleware.forwardauth.authResponseHeadersRegex=^X-Auth-"
        - "traefik.http.middlewares.storage-stripprefix-middleware.stripprefix.prefixes=/api,/storage"
        - "traefik.http.middlewares.storage-retry-middleware.retry.attempts=4"
        - "traefik.http.routers.storage-router.middlewares=storage-auth-middleware,storage-stripprefix-middleware,storage-retry-middleware"
        - "traefik.http.routers.storage-public-router.rule=PathPrefix(`/api/storage/public`)"
        - "traefik.http.routers.storage-public-router.entrypoints=http"
        - "traefik.http.routers.storage-public-router.middlewares=storage-stripprefix-middleware,storage-retry-middleware"
        - "traefik.http.routers.storage-version-router.rule=Path(`/storage/git.json`)"
        - "traefik.http.routers.storage-version-router.entrypoints=http"
        - "traefik.http.routers.storage-version-router.middlewares=storage-stripprefix-middleware"

    logging:
      driver: "journald"
      options:
        tag: chat-storage
    volumes:
      - ./storage.yml:/etc/storage.yml
      - /mnt/chat-minio/data:/data

    command: ["-config=/etc/storage.yml"]

networks:
  backend:
    driver: overlay
