version: '3.7'

services:
  video-proxy:
    image: nkonev/chat-video-proxy:latest
    networks:
      backend:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.video-proxy-service.loadbalancer.server.port=7000"
        - "traefik.http.routers.video-proxy-router.rule=PathPrefix(`/api/video`)"
        - "traefik.http.routers.video-proxy-router.entrypoints=http"
        - "traefik.http.middlewares.video-proxy-stripprefix-middleware.stripprefix.prefixes=/api,/video-proxy,/video"
        - "traefik.http.routers.video-proxy-router.middlewares=auth-middleware@file,video-proxy-stripprefix-middleware"

        - "traefik.http.routers.video-proxy-version-router.rule=Path(`/video-proxy/git.json`)"
        - "traefik.http.routers.video-proxy-version-router.entrypoints=http"
        - "traefik.http.routers.video-proxy-version-router.middlewares=video-proxy-stripprefix-middleware"
    logging:
      driver: "journald"
      options:
        tag: chat-video-proxy
    environment:
#      - GODEBUG=netdns=2
        - VIDEO_PROXY_URLSSOURCE.TYPE=dnsA
        - VIDEO_PROXY_URLSSOURCE.DNSA.NAMETOLOOKUP=video
        - VIDEO_PROXY_URLSSOURCE.DNSA.PROTOCOL=http
        - VIDEO_PROXY_URLSSOURCE.DNSA.PORT=7001

networks:
  backend:
    driver: overlay
