version: '3.7'

services:
  storage:
    image: nkonev/chat-storage:latest
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.storage-service.loadbalancer.server.port=1236"
        - "traefik.http.routers.storage-router.rule=PathPrefix(`/api/storage`)"
        - "traefik.http.routers.storage-router.entrypoints=http"
        - "traefik.http.routers.storage-router.middlewares=auth-middleware@file,api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.routers.storage-public-router.rule=PathPrefix(`/api/storage/public`)"
        - "traefik.http.routers.storage-public-router.entrypoints=http"
        - "traefik.http.routers.storage-public-router.middlewares=api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.middlewares.storage-stripprefix-middleware.stripprefix.prefixes=/storage"
        - "traefik.http.routers.storage-version-router.rule=Path(`/storage/git.json`)"
        - "traefik.http.routers.storage-version-router.entrypoints=http"
        - "traefik.http.routers.storage-version-router.middlewares=storage-stripprefix-middleware"

    logging:
      driver: "journald"
      options:
        tag: chat-storage
    volumes:
      - ./storage.yml:/etc/storage.yml
      - /mnt/chat-minio/data:/data

    command: ["-config=/etc/storage.yml"]

networks:
  backend:
    driver: overlay
