version: '3.7'

services:
  frontend:
    image: nkonev/chat-frontend:latest
    networks:
      backend:
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
    logging:
      driver: "journald"
      options:
        tag: chat-nginx

networks:
  backend:
    driver: overlay
