version: '3.7'

services:
  video:
    image: nkonev/chat-video:latest
    networks:
      backend:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.video-service.loadbalancer.server.port=1237"

        - "traefik.http.routers.video-router.rule=PathPrefix(`/api/video`)"
        - "traefik.http.routers.video-router.entrypoints=http"
        - "traefik.http.routers.video-router.middlewares=auth-middleware@file,api-strip-prefix-middleware@file,retry-middleware@file"

        - "traefik.http.middlewares.video-stripprefix-middleware.stripprefix.prefixes=/video"
        - "traefik.http.routers.video-version-router.rule=Path(`/video/git.json`)"
        - "traefik.http.routers.video-version-router.entrypoints=http"
        - "traefik.http.routers.video-version-router.middlewares=video-stripprefix-middleware"

    logging:
      driver: "journald"
      options:
        tag: chat-video

networks:
  backend:
    driver: overlay
