version: '3.7'

services:
  traefik:
    image: traefik:v2.8.7
    hostname: traefik
    # The Static Configuration
    command: --configFile=/traefik_conf/traefik.yml
    ports:
      - 8081:80
#      - 8010:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_conf:/traefik_conf
    networks:
      - traefik_backend
      - backend
    logging:
      driver: "journald"
      options:
        tag: chat-traefik

  postgresql:
    image: postgres:14.5-alpine3.16
    volumes:
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-postgresql

  redis:
    image: redis:7.0.4-alpine3.16
    hostname: redis
    volumes:
      - redis_data_dir:/data
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-redis

  minio:
    image: bitnami/minio:2022.8.11-debian-11-r0
    hostname: minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - /mnt/chat-minio/data:/data
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-minio

  rabbitmq:
    image: rabbitmq:3.9.22-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=videoChat
      - RABBITMQ_DEFAULT_PASS=videoChatPazZw0rd
    volumes:
      - rabbitmq_data_dir:/var/lib/rabbitmq/mnesia
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-rabbitmq

  livekit:
    image: livekit/livekit-server:v1.2.5
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    networks:
      backend:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.livekit-service.loadbalancer.server.port=7880"
        - "traefik.http.routers.livekit-router.rule=PathPrefix(`/api/livekit`)"
        - "traefik.http.routers.livekit-router.entrypoints=http"
        - "traefik.http.middlewares.livekit-stripprefix-middleware.stripprefix.prefixes=/api/livekit"
        - "traefik.http.routers.livekit-router.middlewares=auth-middleware@file,livekit-stripprefix-middleware,retry-middleware@file"
    ports:
      # turn udp port
      - target: 3478
        published: 3478
        protocol: udp
        mode: host

      # turn tls port
#      - target: 5349
#        published: 5349
#        protocol: tcp
#        mode: host

      # webrtc udp port
      - target: 7882
        published: 7882
        protocol: udp
        mode: host

      # webrtc tcp port
#      - target: 7881
#        published: 7881
#        protocol: tcp
#        mode: host

    logging:
      driver: "journald"
      options:
        tag: chat-livekit

  egress:
    image: nkonev/egress:v1.5.1-pre-3
    networks:
      backend:
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress/config.yaml
    volumes:
      - ./egress/config.yaml:/etc/egress/config.yaml
      - egress_tmp:/tmp/lkegress
    logging:
      driver: "journald"
      options:
        tag: chat-egress

  jaeger:
    image: jaegertracing/all-in-one:1.34.0
    hostname: jaeger
    networks:
      backend:
    logging:
      driver: "journald"
      options:
        tag: chat-jaeger

volumes:
  postgres_data:
  redis_data_dir:
  rabbitmq_data_dir:
  egress_tmp:

networks:
  backend:
    driver: overlay
  traefik_backend:
    external: true
    name: proxy_backend
