server:
  address: ":1236"
  shutdown.timeout: "10s"
  body.limit: "100G"
  contextPath: "/api"

auth:
  exclude:
    - "^/storage/public.*"

jaeger:
  endpoint: "jaeger:6831"

minio:
  endpoint: minio:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  location: "europe-east"
  bucket:
    avatar: "avatar"