server:
  address: ":1236"
  shutdown.timeout: "10s"
  body.limit: "100G"
  contextPath: "/api"
  url: http://api.site.local:8080

auth:
  exclude:
    - "^/storage/public.*"

jaeger:
  endpoint: "jaeger:6831"

minio:
  endpoint: minio:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  location: "europe-east"
  bucket:
    avatar: "avatar"
    files: "files"
    embedded: "embedded"

chat:
  url:
    base: "http://chat:1235"
    access: "/internal/access"
    removeFileItem: "/internal/removeFileItem"
aaa:
  url:
    base: "http://aaa:8060"
    getUsers: "/internal/user/list"

limits:
  stat:
    dir: "/data"
  default:
    per:
      user:
        # 512 megabytes
        max: 536870912