server:
  address: ":1235"
  shutdown.timeout: "10s"
  body.limit: "100G"

http:
  idle:
    conns:
      max: 2
    connTimeout: '10s'
  disableCompression: false

auth:
  exclude:
    - "^/public.*"

postgresql:
  url: "postgres://chat:chatPazZw0rd@localhost:35432/chat?sslmode=disable"
  maxOpenConnections: 16
  maxIdleConnections: 2
  maxLifetime: 15m