server:
  address: ":1235"
  shutdown.timeout: "10s"
  body.limit: "100G"

http:
  idle:
    conns:
      max: 2
    connTimeout: '10s'
  disableCompression: false

auth:
  url: "http://localhost:8070/api/profile"
  exclude:
    - "^/public.*"