http:
  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8082
    aaa-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8060
    chat-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1235
    storage-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1236
    video-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1237
    livekit-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:7880
    event-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:1238

  routers:
    frontend-router:
      rule: "PathPrefix(`/`)"
      service: frontend-service
      middlewares:
        - "retry-middleware"
    aaa-router:
      rule: "PathPrefix(`/api/login`) || Path(`/api/logout`) || PathPrefix(`/api/profile`) || PathPrefix(`/api/user`) || PathPrefix(`/api/oauth2`)"
      service: aaa-service
      middlewares:
        - "retry-middleware"
    chat-router:
      rule: "PathPrefix(`/api/chat`)"
      service: chat-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-router:
      rule: "PathPrefix(`/api/storage`)"
      service: storage-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    video-router:
      rule: "PathPrefix(`/api/video`)"
      service: video-service
      middlewares:
        - "auth-middleware"
        - "api-strip-prefix-middleware"
    chat-public-router:
      rule: "PathPrefix(`/api/chat/public`)"
      service: chat-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    storage-public-router:
      rule: "PathPrefix(`/api/storage/public`)"
      service: storage-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"
    livekit-router:
      rule: "PathPrefix(`/api/livekit`)"
      service: livekit-service
      middlewares:
        - "livekit-strip-prefix-middleware"
        - "retry-middleware"
    event-graphql-router:
      rule: "PathPrefix(`/event/playground`) || PathPrefix(`/api/event/graphql`)"
      service: event-service
      middlewares:
        - "auth-middleware"
        - "retry-middleware"
    event-public-router:
      rule: "PathPrefix(`/api/event/public`)"
      service: event-service
      middlewares:
        - "api-strip-prefix-middleware"
        - "retry-middleware"

  middlewares:
    api-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api"
    livekit-strip-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/api/livekit"
    retry-middleware:
      retry:
        attempts: 4
    auth-middleware:
      forwardAuth:
        address: "http://host.docker.internal:8060/internal/profile"
        authRequestHeaders:
          - "Cookie"
          - "uber-trace-id"
        authResponseHeadersRegex: "^X-Auth-"
