server:
  address: ":1236"
  shutdown.timeout: "10s"
  body.limit: "100G"
  contextPath: "/api"
  url: http://localhost:1236

auth:
  exclude:
    - "^/storage/public.*"

jaeger:
  endpoint: "localhost:6831"

minio:
  endpoint: 127.0.0.1:9000
  accessKeyId: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  location: "europe-east"
  bucket:
    avatar: "avatar"
    files: "files"

chat:
  url:
    base: "http://localhost:1235"
    access: "/internal/access"

limits:
  stat:
    dir: "."
  default:
    per:
      user:
        # 512 megabytes
        max: 536870912