# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install software
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          curl https://raw.githubusercontent.com/vishnubob/wait-for-it/8ed92e8cab83cfed76ff012ed4a36cef74b28096/wait-for-it.sh > ${HOME}/bin/wait-for-it.sh && chmod +x ${HOME}/bin/wait-for-it.sh
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Start & wait docker-compose environment
        run: |
          docker-compose up -d
          wait-for-it.sh -t 30 127.0.0.1:35432 -- echo 'postgres is up'
          wait-for-it.sh -t 30 127.0.0.1:36379 -- echo 'redis is up'
      - name: Build with Maven
        run: |
          (cd aaa; ./mvnw clean package -Dcustom.selenium.headless=true)
      - name: deploy
        if: github.ref == 'refs/heads/master'
        run: echo Deploying
